allowBuilds:
  better-sqlite3: false
  core-js-pure: false
  dtrace-provider: false
  protobufjs: false
  re2: false
ignoredBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - protobufjs
  - re2
