name: Test

permissions: {}

on:
  push:
  pull_request:

jobs:
  ci-optimization:
    name: CI optimization
    uses: dargmuesli/github-actions/.github/workflows/ci-optimization.yml@89c813758dd4c98d28fe3e8d0c8c13923524b4f0 # 5.5.1
    permissions:
      pull-requests: read
  test:
    needs: ci-optimization
    if: needs.ci-optimization.outputs.continue == 'true'
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout git repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Setup package manager
      run: corepack enable

    - name: Setup Node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        cache: pnpm
        node-version: 24

    - name: Install dependencies
      run: pnpm install

    - name: Test
      run: |
        pnpm test
